### ISSUE TITLE
Setting alpha.particles field for fluidized bed reactor

### ISSUE THREAD

**Issue by alnajihu** [lavdwall/catchyFOAM#1]
Greetings,

I am trying to model a fluidized bed reactor using the catchyMultiphaseEulerFoam solver. I modified the tutuorials in the packedBedValidation folder by adding the setFieldsDict in the system folder. However, the solver does not read the setFieldsDict when I run the code, it only reads the initial values for alpha.gas and alpha.particles in the '0' folder, and so the whole bed is initiated with those values.
Could you please guide me on how to modify the tutorial to model a fluidized bed reactor with changing alpha values.

Thank you for help
Regards

**Comment by lavdwall** [comment]
Hi,
Did you execute setFields first? The catchyMultiphaseEulerFoam solver doesn't take into account setFieldsDict (nor does any other native OpenFOAM solver). You would have to run setFields first to change the initial values of alpha.gas and alpha.particles.
I hope this helps?
Best regards
Laurien

**Comment by alnajihu** [comment]
> Hi,
> Did you execute setFields first? The catchyMultiphaseEulerFoam solver doesn't take into account setFieldsDict (nor does any other native OpenFOAM solver). You would have to run setFields first to change the initial values of alpha.gas and alpha.particles.
> I hope this helps?
> Best regards
> Laurien
1
Yes, you're right, I forgot to run the setFields command. Now, it works perfectly. Thank you !
